[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/mcp/*"
  to = "/.netlify/functions/mcp?key=:splat"
  status = 200

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

