/**
 * KI-30 — freshness guard for the generated glyph-advance table
 * (netlify/lib/image-annotate/font-metrics-data.ts).
 *
 * That file is generated by scripts/generate-font-metrics.mts, parsing
 * render-service/fonts/*.ttf directly. If one of those font files is ever swapped without
 * re-running the generator, `resolve.ts`'s `defaultMeasureText` would silently measure
 * against a table that no longer matches the bytes render-service actually serves — exactly
 * the kind of silent drift `tests/agent-artifact-image-annotate-goldens.test.ts`'s `fonts.json`
 * golden already exists to catch for the raw font files themselves (see its "bundled font
 * files are hashed" test). This test extends that idea to the DERIVED table: each face's own
 * `sourceSha256` (embedded by the generator) must match a fresh hash of the live file.
 *
 * A failure here means: run `npx tsx scripts/generate-font-metrics.mts` and commit the
 * regenerated netlify/lib/image-annotate/font-metrics-data.ts alongside the font change.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { FONT_METRICS_TABLE, type BundledFaceId } from "../netlify/lib/image-annotate/font-metrics-data.js";

const FONT_DIR = path.join(process.cwd(), "render-service", "fonts");

const FACE_FILES: Record<BundledFaceId, string> = {
  "NotoSans-Regular": "NotoSans-Regular.ttf",
  "NotoSans-Bold": "NotoSans-Bold.ttf",
  "NotoSerif-Regular": "NotoSerif-Regular.ttf",
  "NotoSerif-Bold": "NotoSerif-Bold.ttf",
  "NotoSansHebrew-Regular": "NotoSansHebrew-Regular.ttf",
  "NotoSansHebrew-Bold": "NotoSansHebrew-Bold.ttf",
};

function sha256File(file: string): string {
  return createHash("sha256").update(readFileSync(file)).digest("hex");
}

test("font-metrics-data.ts: every face's embedded sourceSha256 matches the live render-service/fonts/*.ttf it was generated from", () => {
  const faceIds = Object.keys(FACE_FILES) as BundledFaceId[];
  assert.deepEqual(
    Object.keys(FONT_METRICS_TABLE).sort(),
    faceIds.slice().sort(),
    "font-metrics-data.ts must carry exactly the six bundled faces this test knows about — if a face was added/removed, update both this test and scripts/generate-font-metrics.mts's FACES list"
  );

  for (const faceId of faceIds) {
    const file = path.join(FONT_DIR, FACE_FILES[faceId]);
    const liveHash = sha256File(file);
    const embeddedHash = FONT_METRICS_TABLE[faceId].sourceSha256;
    assert.equal(
      embeddedHash,
      liveHash,
      `netlify/lib/image-annotate/font-metrics-data.ts's "${faceId}" table was generated from a DIFFERENT render-service/fonts/${FACE_FILES[faceId]} than what is on disk now ` +
        `(embedded sourceSha256=${embeddedHash}, live=${liveHash}). Regenerate with: npx tsx scripts/generate-font-metrics.mts`
    );
  }
});

test("font-metrics-data.ts: unitsPerEm is a sane positive integer for every face", () => {
  for (const [faceId, face] of Object.entries(FONT_METRICS_TABLE)) {
    assert.ok(Number.isInteger(face.unitsPerEm) && face.unitsPerEm > 0, `${faceId}: unitsPerEm must be a positive integer, got ${face.unitsPerEm}`);
  }
});

test("font-metrics-data.ts: every advance width is a non-negative finite number", () => {
  for (const [faceId, face] of Object.entries(FONT_METRICS_TABLE)) {
    const codepoints = Object.keys(face.advances);
    assert.ok(codepoints.length > 100, `${faceId}: expected at least 100 covered codepoints, got ${codepoints.length}`);
    for (const cp of codepoints) {
      const advance = face.advances[cp];
      assert.ok(Number.isFinite(advance) && advance! >= 0, `${faceId}: codepoint ${cp} has a bad advance width ${advance}`);
    }
  }
});
