import { projectBlobStore } from "./blob-store.js";
import { sha256Hex, type ArtifactKind, type ArtifactReference, type SaveArtifactBytesInput } from "./artifact-core/index.js";
import { resolveArtifactFilenameCollision, writeArtifactReferenceIndexes } from "./artifact-core/artifact-index.js";
import { projectStoreNames } from "./project-descriptor.js";

/**
 * THE canonical artifact blob layout — one layout for every caller, no per-client key
 * schemes (this is the layout the dr-lurie adapter used; with the adapters deleted it is
 * simply pdf-tool's layout):
 *
 *   {artifactKind}/{safeRequestId}/{sha256}{ext}
 *
 * The same for generated and edited artifacts (no /edits/ segment). Parsing a key back
 * proves it was produced by this deterministic layout rather than hand-authored — the
 * verification API leans on that. Bytes land in the caller's `artifacts` store and index
 * entries in the caller's `artifactIndex` store, both named by the active storage grant.
 */

/** The pieces the canonical blob-key layout binds together. `requestSegment` is the request
 * id exactly as it appears in the key (after path sanitization), so verification can compare
 * it against safeRequestSegment(requestId). */
export interface ArtifactBlobKeyParts {
  artifactKind?: ArtifactKind;
  requestSegment: string;
  sha256: string;
}

const CANONICAL_ARTIFACT_KINDS: ArtifactKind[] = ["image", "pdf", "binary"];

function safePathSegment(value: string): string {
  const safe = value.trim().replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
  if (!safe) throw new Error("Invalid empty path segment");
  return safe;
}

/** The path-safe form of a request id as it appears inside canonical blob keys. */
export function safeRequestSegment(requestId: string): string {
  return safePathSegment(requestId);
}

/** Parses a canonical blob key back into the parts it binds, or null when the key is not in
 * the canonical layout (e.g. a hand-authored or foreign key). */
export function parseArtifactBlobKey(blobKey: string): ArtifactBlobKeyParts | null {
  if (typeof blobKey !== "string") return null;
  const match = blobKey.match(/^([a-z]+)\/(.+)\/([a-f0-9]{64})(\.[a-z0-9]+)?$/);
  if (!match) return null;
  const [, kind, requestSegment, sha256] = match;
  if (!requestSegment || requestSegment.includes("/")) return null;
  const artifactKind = (CANONICAL_ARTIFACT_KINDS as string[]).includes(kind) ? (kind as ArtifactKind) : undefined;
  return { artifactKind, requestSegment, sha256 };
}

function extensionForContentType(contentType: string, filename: string): string {
  const lower = filename.toLowerCase();
  if (contentType === "image/png" && !lower.endsWith(".png")) return ".png";
  if (contentType === "image/jpeg" && !lower.endsWith(".jpg") && !lower.endsWith(".jpeg")) return ".jpg";
  if (contentType === "image/webp" && !lower.endsWith(".webp")) return ".webp";
  if (contentType === "application/pdf" && !lower.endsWith(".pdf")) return ".pdf";
  const match = lower.match(/\.[a-z0-9]+$/);
  return match?.[0] ?? "";
}

function validateBytes(input: SaveArtifactBytesInput, bytes: Buffer): void {
  if (bytes.byteLength === 0) throw new Error("Artifact bytes are empty");
  if (input.artifactKind === "image") {
    const isPng = bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
    const isJpeg = bytes.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff]));
    const isWebp = bytes.subarray(0, 4).toString("ascii") === "RIFF" && bytes.subarray(8, 12).toString("ascii") === "WEBP";
    if (!isPng && !isJpeg && !isWebp) throw new Error("Unsupported or invalid image bytes");
    if (input.contentType === "image/png" && !isPng) throw new Error("Image contentType does not match generated bytes");
    if (input.contentType === "image/jpeg" && !isJpeg) throw new Error("Image contentType does not match generated bytes");
    if (input.contentType === "image/webp" && !isWebp) throw new Error("Image contentType does not match generated bytes");
  }
  if (input.artifactKind === "pdf" && bytes.subarray(0, 5).toString("ascii") !== "%PDF-") throw new Error("Unsupported or invalid PDF bytes");
}

/**
 * Persists artifact bytes into the caller's `artifacts` store under the canonical layout
 * and writes every retained index (request-artifacts, by-request, by-kind, by-tag, and —
 * when a slot/filename applies — by-slot, latest-by-slot, by-filename) into the caller's
 * `artifactIndex` store. Store names and credentials come from the active storage grant
 * (plus descriptor storeNames gaps); pdf-tool holds none of its own.
 */
export async function saveArtifactBytes(input: SaveArtifactBytesInput): Promise<ArtifactReference> {
  const bytes = Buffer.from(input.bytes);
  validateBytes(input, bytes);
  // The stored sha256 is ALWAYS the digest of the bytes actually written. A caller-supplied
  // sha256 is a claim about those bytes, re-verified here rather than trusted: a mismatch
  // means the caller hashed something other than what it is storing (a bug), and storing
  // the wrong digest would make every downstream verification lie.
  const computedSha256 = sha256Hex(bytes);
  if (input.sha256 !== undefined && input.sha256 !== computedSha256) {
    throw new Error(`Artifact sha256 mismatch: caller supplied ${input.sha256} but the bytes hash to ${computedSha256}`);
  }
  const sha256 = computedSha256;
  const requestId = safePathSegment(input.requestId);
  const kind = safePathSegment(input.artifactKind);
  const extension = extensionForContentType(input.contentType, input.filename);
  // blobKey stays purely content-addressed (kind/requestId/sha256+ext) — collision handling
  // below only ever changes the DISPLAY name used for the by-filename index and the stored
  // reference, never the blob's own key or its sha256.
  const blobKey = `${kind}/${requestId}/${sha256}${extension}`;
  const stores = projectStoreNames();
  // Collision handling: a by-filename pointer already at {projectId, requestId, filename}
  // for DIFFERENT bytes gets -2, -3, ... appended until an unused name is found. Identical
  // bytes resubmitted under the same or a similar name are never renamed — the loop returns
  // the existing name the moment it finds a pointer whose sha256 already matches, which is
  // exactly today's same-bytes-same-name dedupe behavior, preserved unchanged.
  const resolvedFilename = input.filename
    ? await resolveArtifactFilenameCollision(input.projectId, input.requestId, input.filename, sha256, { storeName: stores.artifactIndex })
    : input.filename;
  const artifact: ArtifactReference = {
    blobKey,
    sizeBytes: bytes.byteLength,
    sha256,
    contentType: input.contentType,
    createdAtISO: new Date().toISOString(),
    artifactKind: input.artifactKind,
    originalFilename: input.filename,
    filename: resolvedFilename,
    label: input.label,
    tags: input.tags ?? [],
    metadata: input.metadata ?? {}
  };
  const store = await projectBlobStore(stores.artifacts);
  await store.set(blobKey, bytes, { metadata: { requestId: input.requestId, sha256, contentType: input.contentType, artifactKind: input.artifactKind } });
  await store.setJSON(`${blobKey}.json`, artifact);
  await writeArtifactReferenceIndexes(input.requestId, artifact, { storeName: stores.artifactIndex, projectId: input.projectId, slot: input.slot, filename: resolvedFilename });
  return artifact;
}
